name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (React ${{ matrix.react-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react-version:
          - '^16'
          - '^18'
          - '^19'
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - id: setup-react
        name: Setup React
        uses: ./
        with:
          react-version: ${{ matrix.react-version }}
          react-dom-version: ${{ matrix.react-version }}
      - name: Install dependencies
        run: pnpm install
      - name: Test action
        run: |
          if [[ "${{ steps.setup-react.outputs.react-version }}" != ${{ matrix.react-version }}* ]]; then
            exit 1
          fi
          if [[ "${{ steps.setup-react.outputs.react-dom-version }}" != ${{ matrix.react-version }}* ]]; then
            exit 1
          fi
          if [[ "${{ steps.setup-react.outputs.react-types-version }}" != "" ]]; then
            exit 1
          fi
          if [[ "${{ steps.setup-react.outputs.react-dom-types-version }}" != "" ]]; then
            exit 1
          fi
      - if: ${{ matrix.react-version == '^19' }}
        name: Check formatting
        run: pnpm prettier --check "**/*.{json,md,mjs,mts}"
      - if: ${{ matrix.react-version == '^19' }}
        name: Check types
        run: pnpm tsc --noEmit
      - name: Build
        run: pnpm build
      - name: Check dist for changes
        run: git diff --exit-code --quiet ./dist
